kubeconfig: "/home/ch4ser/.kube/config"
ignoreNamespaces:
  - kube-system
  - kube-public
  - default
  - falco
  - cilium-secrets
  - kube-node-lease
database: "postgres://user:pass@localhost:5432/kubefix"
observeTime: 10
resourceDir: "./exported-resources"
lintDir: "./lint-results"
fixDir: "./fix-results"
validateDir: "./validate-results"
llmApi: "http://localhost:8000/fix"
